import React, {useCallback, useEffect, useRef, useState, type ReactNode} from 'react';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import useBaseUrl from '@docusaurus/useBaseUrl';
import {Check, Copy, Download} from 'lucide-react';
import {Button} from '@site/src/components/ui/button';
import manifest from '@site/src/data/postman.json';

type Entry = {file: string; label: string; requests: number; uid?: string};
type Manifest = {environment: string; workspace?: string; modules: Record<string, Entry>};

/**
 * A module's Postman collection, as a file to download and as a URL to
 * import. Both are served by this site, so neither depends on Postman: any
 * client that reads a v2.1 collection takes it. "Run in Postman" appears only
 * once the collection is published to NHA's public workspace, as an outbound
 * link like the sandbox's.
 *
 * Generated by scripts/build-postman.mjs. A module with no collection renders
 * nothing.
 */
export default function PostmanCollection({module}: {module: string}): ReactNode {
  const {environment, workspace, modules} = manifest as Manifest;
  const entry = modules[module];
  const {siteConfig} = useDocusaurusContext();
  const file = useBaseUrl(`/postman/${entry?.file ?? ''}`);
  const env = useBaseUrl(`/postman/${environment}`);
  const importUrl = `${siteConfig.url.replace(/\/$/, '')}${file}`;
  const [copied, setCopied] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  useEffect(() => () => clearTimeout(timer.current), []);

  const copy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(importUrl);
      setCopied(true);
      clearTimeout(timer.current);
      timer.current = setTimeout(() => setCopied(false), 2000);
    } catch {
      // No clipboard: the URL is on screen to select by hand.
    }
  }, [importUrl]);

  if (!entry) return null;
  const run =
    entry.uid && workspace
      ? `https://app.getpostman.com/run-collection/${entry.uid}?action=collection%2Ffork&collection-url=${encodeURIComponent(
          `entityId=${entry.uid}&entityType=collection&workspaceId=${workspace}`,
        )}`
      : undefined;

  return (
    <div className="not-prose my-6 rounded-lg border border-border bg-surface p-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="text-sm text-muted-foreground">
          {entry.requests} requests in the order you build them, and a sandbox environment to fill in.
          Each step keeps the txnId and X-token it gets back for the steps after it.
        </div>
        <div className="flex flex-wrap gap-2">
          <Button asChild size="sm">
            <a href={file} download>
              <Download aria-hidden="true" />
              Collection
            </a>
          </Button>
          <Button asChild size="sm" variant="outline">
            <a href={env} download>
              <Download aria-hidden="true" />
              Environment
            </a>
          </Button>
          {run && (
            <Button asChild size="sm" variant="outline">
              <a href={run} target="_blank" rel="noopener noreferrer">
                Run in Postman
              </a>
            </Button>
          )}
        </div>
      </div>
      <div className="mt-3 flex items-center gap-2 rounded-md border border-border bg-surface-sunken px-3 py-1.5">
        <code className="min-w-0 flex-1 truncate border-0 bg-transparent p-0 text-sm">{importUrl}</code>
        <Button size="icon-sm" variant="ghost" onClick={copy} aria-label="Copy the import URL">
          {copied ? <Check aria-hidden="true" /> : <Copy aria-hidden="true" />}
        </Button>
      </div>
      <p className="mt-2 mb-0 text-sm text-muted-foreground">
        Postman, Insomnia, Hoppscotch and Bruno take this through Import, as a link or as the downloaded file.
      </p>
      <span className="sr-only" role="status" aria-live="polite">
        {copied ? 'Import URL copied' : ''}
      </span>
    </div>
  );
}
