import {existsSync, readFileSync, readdirSync} from 'node:fs';
import {join} from 'node:path';
import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import type {ScalarOptions} from '@scalar/docusaurus';
import apiTree from './src/data/api-sidebar.json';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Tailwind v4 runs as a PostCSS plugin; Docusaurus exposes the PostCSS chain
// through this hook, so no separate build step is needed.
function tailwindPlugin() {
  return {
    name: 'tailwind-plugin',
    configurePostCss(postcssOptions: {plugins: unknown[]}) {
      postcssOptions.plugins = [require('@tailwindcss/postcss')];
      return postcssOptions;
    },
  };
}

// Static assets (specs, the vendored Scalar bundle) are addressed with
// absolute paths, so they must carry the base path when the site is
// served under one, e.g. GitHub Pages at /abdm-docs/.
const siteBase = process.env.DOCUSAURUS_BASE_URL ?? '/';

// One interactive reference per specification file, discovered from the
// catalogue tree: dropping a YAML under catalogue/openapi/<platform>/<version>
// publishes its Scalar reference at /reference/<filename-stem>. Every instance
// is self-hosted: the bundle is vendored, and Scalar's cloud services stay off.
function listSpecFiles(dir: string): string[] {
  return readdirSync(dir, {withFileTypes: true}).flatMap((entry) => {
    if (entry.isDirectory()) {
      return entry.name.startsWith('.') ? [] : listSpecFiles(join(dir, entry.name));
    }
    return /\.(yaml|json)$/.test(entry.name) ? [entry.name] : [];
  });
}
const references = listSpecFiles(join(__dirname, '../catalogue/openapi')).map((file) => {
  const id = file.replace(/\.(yaml|json)$/, '');
  return {id, label: id, spec: file};
});

const scalarPlugins = references.map(
  (reference) =>
    [
      '@scalar/docusaurus',
      {
        id: reference.id,
        label: reference.label,
        route: `/reference/${reference.id}`,
        showNavLink: false,
        // Serve the reference bundle from our own origin, not jsdelivr.
        // Vendored by scripts/sync-specs.mjs from @scalar/api-reference.
        cdn: `${siteBase}vendor/scalar/standalone.js`,
        configuration: {
          url: `${siteBase}specs/${reference.spec}`,
          // Self-hosted: no Scalar cloud services. "Try it" requests go
          // directly from the browser, so target APIs must allow CORS, or
          // proxyUrl must point to a proxy in our own infrastructure
          // (Scalar's proxy server is open source and self-hostable).
          proxyUrl: '',
          telemetry: false,
          // Links to client.scalar.com, a hosted service.
          hideClientButton: true,
          agent: {
            disabled: true,
          },
          showDeveloperTools: 'never',
        },
      } as ScalarOptions,
    ],
);

// ---------------------------------------------------------------------------
// Sidebar shaping. Sidebars are autogenerated from the docs tree (sidebars.ts);
// the two rules the tree cannot express live here: a version root's api/ and
// reference/ folders belong to the API references tab, not the overview, and
// a module's endpoints folder renders as its use-case groups from
// api-sidebar.json rather than a flat alphabetical list.

function firstDocId(item: any): string | undefined {
  if (item.type === 'doc') return item.id;
  if (item.type === 'category') {
    if (item.link?.type === 'doc') return item.link.id;
    for (const child of item.items ?? []) {
      const id = firstDocId(child);
      if (id) return id;
    }
  }
  return undefined;
}

/** The use-case groups build-api-reference.mjs recorded for one module. */
function useCaseGroups(moduleDir: string): any[] {
  const module = (apiTree as any[]).find((entry) => entry.moduleDir === moduleDir);
  return (module?.groups ?? []).map((group: any) =>
    group.children
      ? {
          type: 'category',
          label: group.label,
          collapsed: true,
          items: group.children.map((child: any) => ({
            type: 'category',
            label: child.label,
            collapsed: true,
            items: child.items,
          })),
        }
      : {type: 'category', label: group.label, collapsed: true, items: group.items},
  );
}

/** True when a module folder carries its own hand-written APIs page. */
function hasApisDoc(moduleDir: string): boolean {
  return ['mdx', 'md'].some((ext) =>
    existsSync(join(__dirname, 'docs', `${moduleDir}/apis.${ext}`)),
  );
}

/**
 * Swap every generated endpoints folder for one APIs category holding the
 * module's use-case groups.
 *
 * The groups used to be spread into the module, which made them siblings of
 * User journey and Errors, so a module read as one long list with no way to
 * tell a guide page from an endpoint group. Every module now has the same
 * three rungs: User journey, APIs, Errors.
 */
function spliceEndpoints(items: any[]): any[] {
  const out = items.flatMap((item: any) => {
    if (item.type !== 'category') return [item];
    const id = firstDocId(item);
    if (item.label === 'Endpoints' && id && id.includes('/endpoints/')) {
      const moduleDir = id.slice(0, id.indexOf('/endpoints/'));
      return [
        {
          type: 'category',
          label: 'APIs',
          collapsed: false,
          // Where the module has an APIs page, the category header opens it
          // rather than sitting beside it as a second entry with the same name.
          ...(hasApisDoc(moduleDir)
            ? {link: {type: 'doc', id: `${moduleDir}/apis`}}
            : {}),
          items: useCaseGroups(moduleDir),
        },
      ];
    }
    return [{...item, items: spliceEndpoints(item.items ?? [])}];
  });
  // The APIs page is now the category's link, so drop the loose doc entry.
  const linked = new Set(
    out
      .filter((i: any) => i.type === 'category' && i.label === 'APIs' && i.link?.id)
      .map((i: any) => i.link.id),
  );
  return linked.size === 0
    ? out
    : out.filter((i: any) => !(i.type === 'doc' && linked.has(i.id)));
}

async function sidebarItemsGenerator({defaultSidebarItemsGenerator, ...args}: any) {
  const items = await defaultSidebarItemsGenerator(args);
  const dirName: string = args.item.dirName;
  if (/^[^/]+\/[^/]+$/.test(dirName)) {
    // A version root is the overview sidebar; its api/ and reference/
    // folders render in the API references tab instead.
    return items.filter((item: any) => {
      const id = firstDocId(item);
      return !(
        id &&
        (id.startsWith(`${dirName}/api/`) || id.startsWith(`${dirName}/reference/`))
      );
    });
  }
  if (dirName.endsWith('/api')) {
    return spliceEndpoints(items);
  }
  return items;
}

const catalogueVersion = readFileSync(
  join(__dirname, '../catalogue/VERSION'),
  'utf8',
).trim();

const config: Config = {
  title: 'ABDM Developer Portal',
  tagline: 'One catalogue of ABDM, readable by humans and machines',
  // The national emblem, not Docusaurus's own mark. One SVG for both themes:
  // a browser cannot choose between a light and a dark icon the way the page
  // chrome does, so the file carries its own prefers-color-scheme rule.
  favicon: 'img/favicon.svg',

  // Safari does not take an SVG favicon, so a raster of the same emblem is
  // offered alongside it. `alternate icon` is only reached by a browser that
  // could not use the SVG, so Chrome, Firefox and Edge still get the vector
  // and its light and dark variants.
  headTags: [
    {
      tagName: 'link',
      attributes: {
        rel: 'alternate icon',
        type: 'image/png',
        href: `${process.env.DOCUSAURUS_BASE_URL ?? '/'}img/favicon.png`,
      },
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'apple-touch-icon',
        href: `${process.env.DOCUSAURUS_BASE_URL ?? '/'}img/apple-touch-icon.png`,
      },
    },
  ],

  future: {
    v4: true,
  },

  // The Pages workflow overrides these for the github.io deployment; a
  // custom domain later sets DOCUSAURUS_URL and drops the base path.
  url: process.env.DOCUSAURUS_URL ?? 'https://abdm-docs.example.com',
  baseUrl: process.env.DOCUSAURUS_BASE_URL ?? '/',

  onBrokenLinks: 'throw',

  customFields: {
    // The Docs MCP server's public address. Null until it has one: the install
    // panel on the MCP page renders locked, and every button on it goes live
    // the moment this resolves. Nothing else has to change.
    mcpUrl: process.env.MCP_URL ?? null,
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          sidebarItemsGenerator,
          routeBasePath: '/docs',
          // README.md files are contributor notes for the folder they sit in,
          // shown by GitHub and never rendered as pages. The first entries are
          // Docusaurus's own defaults, which setting `exclude` would drop.
          exclude: [
            '**/_*.{js,jsx,ts,tsx,md,mdx}',
            '**/_*/**',
            '**/*.test.{js,jsx,ts,tsx}',
            '**/__tests__/**',
            '**/README.md',
          ],
          // The tree runs four levels deep under Registries, so the path a
          // reader is on is worth showing.
          breadcrumbs: true,
          showLastUpdateTime: true,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    tailwindPlugin,
    ...scalarPlugins,
    [
      // A reader who types /docs, or follows a link written before the
      // gateway segment existed, lands on the HIE-CM introduction rather
      // than a 404.
      '@docusaurus/plugin-client-redirects',
      {
        redirects: [
          {from: '/docs', to: '/docs/hiecm/v3/'},
          // Old flat and building-blocks URLs from before the folder
          // restructure. The `from` paths are the URLs as they were published,
          // under the platform's old name (abdm); the blanket abdm-to-hiecm
          // alias in createRedirects only covers pages that still exist at the
          // same path, so moved pages need these explicit entries.
          {from: '/docs/abdm/v3/building-blocks/registries', to: '/docs/hiecm/v3/registries/'},
          {from: '/docs/abdm/v3/building-blocks/registries/abha', to: '/docs/hiecm/v3/registries/abha'},
          {from: '/docs/abdm/v3/building-blocks/registries/nhpr', to: '/docs/hiecm/v3/registries/nhpr/'},
          {from: '/docs/abdm/v3/building-blocks/registries/nhpr/hpr', to: '/docs/hiecm/v3/registries/nhpr/hpr'},
          {from: '/docs/abdm/v3/building-blocks/registries/nhpr/hfr', to: '/docs/hiecm/v3/registries/nhpr/hfr'},
          {from: '/docs/abdm/v3/building-blocks/gateway', to: '/docs/hiecm/v3/concepts/gateway'},
          {from: '/docs/abdm/v3/building-blocks/hie-cm', to: '/docs/hiecm/v3/concepts/gateway'},
          {from: '/docs/abdm/v3/concepts/hie-cm', to: '/docs/hiecm/v3/concepts/gateway'},
          {from: '/docs/overview', to: '/docs/hiecm/v3/'},
          {from: '/docs/api', to: '/docs/hiecm/v3/getting-started/milestones'},
          {from: '/docs/abdm/v3/architecture', to: '/docs/hiecm/v3/getting-started/architecture'},
          {from: '/docs/abdm/v3/sandbox', to: '/docs/hiecm/v3/getting-started/sandbox'},
          {from: '/docs/abdm/v3/milestones', to: '/docs/hiecm/v3/getting-started/milestones'},
          {from: '/docs/abdm/v3/what-you-can-build', to: '/docs/hiecm/v3/getting-started/what-you-can-build'},
          {from: '/docs/abdm/v3/glossary', to: '/docs/hiecm/v3/getting-started/glossary'},
          {from: '/docs/abdm/v3/phr', to: '/docs/hiecm/v3/concepts/phr'},
          {from: '/docs/abdm/v3/registries/hpr', to: '/docs/hiecm/v3/registries/nhpr/hpr'},
          {from: '/docs/abdm/v3/registries/hfr', to: '/docs/hiecm/v3/registries/nhpr/hfr'},
          {from: '/docs/uhi/v1/onboarding', to: '/docs/uhi/v1/getting-started/onboarding'},
          {from: '/docs/uhi/v1/glossary', to: '/docs/uhi/v1/getting-started/glossary'},
          {from: '/docs/uhi/v1/network-and-protocol', to: '/docs/uhi/v1/concepts/network-and-protocol'},
          {from: '/docs/nhcx/v1/glossary', to: '/docs/nhcx/v1/getting-started/glossary'},
        ],
        createRedirects(to: string) {
          const aliases: string[] = [];
          // The HIE-CM platform folder was renamed from abdm; every page
          // answers at its old URL too.
          const hiecm = to.match(/^\/docs\/hiecm\/(.+)$/);
          if (hiecm) {
            aliases.push(`/docs/abdm/${hiecm[1]}`);
          }
          // Every UHI service page moved down into concepts/.
          const service = to.match(/^\/docs\/uhi\/v1\/concepts\/services\/(.+)$/);
          if (service) {
            aliases.push(`/docs/uhi/v1/services/${service[1]}`);
          }
          return aliases.length > 0 ? aliases : undefined;
        },
      },
    ],
  ],

  themes: [
    // Open source local search, indexed at build time. No third party service.
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        indexBlog: false,
        docsRouteBasePath: '/docs',
        highlightSearchTermsOnTargetPage: true,
        searchResultLimits: 10,
      },
    ],
    '@docusaurus/theme-mermaid',
  ],

  themeConfig: {
    image: 'img/docusaurus-social-card.jpg',
    colorMode: {
      respectPrefersColorScheme: true,
    },
    docs: {
      sidebar: {
        // The sidebar folds away sideways, which the API pages need: their
        // request panel wants the width more than the tree does.
        hideable: true,
        autoCollapseCategories: false,
      },
    },
    navbar: {
      title: 'ABDM Developer Portal',
      logo: {
        alt: '',
        src: 'img/logo.svg',
        srcDark: 'img/logo-dark.svg',
      },
      hideOnScroll: false,
      items: [
        {
          href: 'https://sandbox.abdm.gov.in',
          label: 'ABDM sandbox',
          position: 'right',
        },
        {
          href: 'https://github.com/eka-care/abdm-docs',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'light',
      links: [
        {
          title: 'Overview',
          items: [
            {label: 'Introduction', to: '/docs/hiecm/v3'},
            {label: 'Sandbox access', to: '/docs/hiecm/v3/getting-started/sandbox'},
            {label: 'Glossary', to: '/docs/hiecm/v3/getting-started/glossary'},
          ],
        },
        {
          title: 'API references',
          items: [
            {label: 'All endpoints', to: '/docs/hiecm/v3/api'},
            {label: 'M1 ABHA identity', to: '/docs/hiecm/v3/api/m1'},
            {label: 'M2 Linking and sharing', to: '/docs/hiecm/v3/api/m2'},
            {label: 'M3 Consent and fetching', to: '/docs/hiecm/v3/api/m3'},
          ],
        },
        {
          title: 'More',
          items: [
            {label: "What's new", to: '/docs/whats-new'},
            {label: 'Support', to: '/docs/support'},
            {label: 'ABDM sandbox', href: 'https://sandbox.abdm.gov.in'},
            {label: 'NHA dev forum', href: 'https://devforum.abdm.gov.in'},
          ],
        },
      ],
      // The catalogue version is in the footer so a reader can tell an agent
      // which version of the documentation they are looking at.
      copyright: `Catalogue ${catalogueVersion} · Copyright © ${new Date().getFullYear()} National Health Authority (NHA). MIT licensed.`,
    },
    prism: {
      theme: prismThemes.oneLight,
      darkTheme: prismThemes.oneDark,
      additionalLanguages: ['bash', 'json', 'yaml', 'java', 'python'],
    },
  } satisfies Preset.ThemeConfig,

  markdown: {
    mermaid: true,
    // .md files are CommonMark, .mdx files are MDX. Content pages are written
    // from NHA documents and contain raw angle brackets and URLs that MDX
    // would try to parse as JSX. A page that wants components uses .mdx.
    format: 'detect',
  },

};

export default config;
