import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {existsSync, readdirSync} from 'node:fs';
import {join} from 'node:path';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebars are the docs tree, not a curated list. Every docs/<platform>/
 * <version> folder gets two sidebars: an overview one holding everything but
 * api/ and reference/, and an API one holding exactly those. Order and labels
 * come from _category_.json files and sidebar_position front matter, so a
 * contributor places a page by where they put the file, never by editing this
 * file. The api/ and reference/ split, and the endpoint use-case grouping,
 * are applied by the sidebarItemsGenerator in docusaurus.config.ts.
 */

const docsRoot = join(__dirname, 'docs');

/**
 * True when a folder holds at least one page the site will render. A folder
 * carrying only a README (a contributor note) or partials is scaffolding for
 * future content and must not become an empty sidebar category, which
 * Docusaurus rejects.
 */
function hasDocs(dir: string): boolean {
  if (!existsSync(dir)) {
    return false;
  }
  return readdirSync(dir, {withFileTypes: true}).some((entry) => {
    if (entry.name.startsWith('_') || entry.name.startsWith('.')) {
      return false;
    }
    if (entry.isDirectory()) {
      return hasDocs(join(dir, entry.name));
    }
    return /\.(md|mdx)$/.test(entry.name) && entry.name !== 'README.md';
  });
}

// Folders that are tabs of their own, not platforms.
const NOT_PLATFORMS = new Set(['whats-new', 'support']);

const sidebars: SidebarsConfig = {
  whatsNewSidebar: [{type: 'autogenerated', dirName: 'whats-new'}],
  supportSidebar: [{type: 'autogenerated', dirName: 'support'}],
};

for (const platform of readdirSync(docsRoot, {withFileTypes: true})) {
  if (
    !platform.isDirectory() ||
    platform.name.startsWith('_') ||
    platform.name.startsWith('.') ||
    NOT_PLATFORMS.has(platform.name)
  ) {
    continue;
  }
  for (const version of readdirSync(join(docsRoot, platform.name), {withFileTypes: true})) {
    if (!version.isDirectory() || version.name.startsWith('_') || version.name.startsWith('.')) {
      continue;
    }
    const pv = `${platform.name}/${version.name}`;
    sidebars[`${platform.name}-${version.name}-overview`] = [
      {type: 'autogenerated', dirName: pv},
    ];

    const apiItems: SidebarsConfig[string] = [];
    if (hasDocs(join(docsRoot, pv, 'api'))) {
      apiItems.push({type: 'autogenerated', dirName: `${pv}/api`});
    }
    if (hasDocs(join(docsRoot, pv, 'reference'))) {
      apiItems.push({
        type: 'category',
        label: 'References',
        collapsed: false,
        items: [{type: 'autogenerated', dirName: `${pv}/reference`}],
      });
    }
    if (apiItems.length > 0) {
      sidebars[`${platform.name}-${version.name}-api`] = apiItems;
    }
  }
}

export default sidebars;
