import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {existsSync, readdirSync} from 'node:fs';
import {join} from 'node:path';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebars are the docs tree, not a curated list. Every docs/<platform>/
 * <version> folder gets three sidebars: an overview one holding everything the
 * other two do not, an API one holding api/, reference/ and troubleshooting/,
 * and a Developer resources one holding resources/.
 * Order and labels come from _category_.json files and sidebar_position front
 * matter, so a contributor places a page by where they put the file, never by
 * editing this file. The split, and the endpoint use-case grouping, are
 * applied by the sidebarItemsGenerator in docusaurus.config.ts.
 */

const docsRoot = join(__dirname, 'docs');

/**
 * True when a folder holds at least one page the site will render. A folder
 * carrying only a README (a contributor note) or partials is scaffolding for
 * future content and must not become an empty sidebar category, which
 * Docusaurus rejects.
 */
function hasDocs(dir: string): boolean {
  if (!existsSync(dir)) {
    return false;
  }
  return readdirSync(dir, {withFileTypes: true}).some((entry) => {
    if (entry.name.startsWith('_') || entry.name.startsWith('.')) {
      return false;
    }
    if (entry.isDirectory()) {
      return hasDocs(join(dir, entry.name));
    }
    return /\.(md|mdx)$/.test(entry.name) && entry.name !== 'README.md';
  });
}

// Folders that are tabs of their own, not platforms.
const NOT_PLATFORMS = new Set(['whats-new', 'support']);

/**
 * Gateways whose API side is split three ways, one tab each: API reference
 * holds only the APIs, FHIR reference only reference/fhir/, and the error
 * code pages show no sidebar at all. Their other reference pages and their
 * troubleshooting move into the Docs sidebar, so every page keeps a home.
 */
const SPLIT_REFERENCE = new Set(['nhcx']);

const sidebars: SidebarsConfig = {
  whatsNewSidebar: [{type: 'autogenerated', dirName: 'whats-new'}],
  supportSidebar: [{type: 'autogenerated', dirName: 'support'}],
};

for (const platform of readdirSync(docsRoot, {withFileTypes: true})) {
  if (
    !platform.isDirectory() ||
    platform.name.startsWith('_') ||
    platform.name.startsWith('.') ||
    NOT_PLATFORMS.has(platform.name)
  ) {
    continue;
  }
  for (const version of readdirSync(join(docsRoot, platform.name), {withFileTypes: true})) {
    if (!version.isDirectory() || version.name.startsWith('_') || version.name.startsWith('.')) {
      continue;
    }
    const pv = `${platform.name}/${version.name}`;
    const split = SPLIT_REFERENCE.has(platform.name);
    sidebars[`${platform.name}-${version.name}-overview`] = [
      {type: 'autogenerated', dirName: pv},
      // On a split gateway, the reference pages that are neither FHIR nor
      // error codes, and troubleshooting, belong to Docs.
      ...(split && hasDocs(join(docsRoot, pv, 'reference'))
        ? [
            {
              type: 'category' as const,
              label: 'Reference',
              className: 'sidebar-icon sidebar-icon--book-open',
              collapsed: true,
              items: [
                {type: 'autogenerated' as const, dirName: `${pv}/reference`},
                // Security audit and Go live are reference material on a split
                // gateway, two entries in Reference, the audit first because it
                // comes before the switch. The folder keeps its place on disk,
                // so neither URL changes.
                ...(hasDocs(join(docsRoot, pv, 'go-live'))
                  ? [
                      {type: 'doc' as const, id: `${pv}/go-live/security-audit`, className: 'sidebar-icon sidebar-icon--shield-check'},
                      {type: 'doc' as const, id: `${pv}/go-live/index`, label: 'Go live', className: 'sidebar-icon sidebar-icon--plane-takeoff'},
                    ]
                  : []),
              ],
            },
          ]
        : []),
      ...(split && hasDocs(join(docsRoot, pv, 'troubleshooting'))
        ? [
            {
              type: 'category' as const,
              label: 'Troubleshooting',
              className: 'sidebar-icon sidebar-icon--life-buoy',
              collapsed: true,
              link: {type: 'doc' as const, id: `${pv}/troubleshooting/index`},
              items: [{type: 'autogenerated' as const, dirName: `${pv}/troubleshooting`}],
            },
          ]
        : []),
    ];
    if (split && hasDocs(join(docsRoot, pv, 'reference', 'fhir'))) {
      sidebars[`${platform.name}-${version.name}-fhir`] = [
        {type: 'autogenerated', dirName: `${pv}/reference/fhir`},
      ];
    }

    const apiItems: SidebarsConfig[string] = [];
    if (hasDocs(join(docsRoot, pv, 'api'))) {
      // Every API collection sits inside one APIs section, the way the
      // reference pages sit inside References. Left flat, the modules were
      // siblings of the sections below them, so the sidebar had two kinds of
      // top level entry and no way to tell them apart.
      // The section header is the index page, so "APIs" opens the list of
      // every operation rather than being a label you have to click past to
      // reach a page called All endpoints saying the same thing.
      if (split) {
        // On a split gateway the tab holds nothing but the APIs, so a section
        // header over them names the tab a second time. The modules sit at
        // the top, under the page that lists every operation.
        apiItems.push(
          {type: 'doc', id: `${pv}/api/index`, label: 'All endpoints', className: 'sidebar-icon sidebar-icon--code-xml'},
          {type: 'autogenerated', dirName: `${pv}/api`},
        );
      } else apiItems.push({
        type: 'category',
        label: 'APIs',
        className: 'sidebar-icon sidebar-icon--code-xml',
        collapsed: false,
        link: {type: 'doc', id: `${pv}/api/index`},
        items: [{type: 'autogenerated', dirName: `${pv}/api`}],
      });
    }
    if (!split && hasDocs(join(docsRoot, pv, 'reference'))) {
      apiItems.push({
        type: 'category',
        label: 'References',
        className: 'sidebar-icon sidebar-icon--book-open',
        collapsed: false,
        items: [{type: 'autogenerated', dirName: `${pv}/reference`}],
      });
    }
    if (!split && hasDocs(join(docsRoot, pv, 'troubleshooting'))) {
      // A reader opens Troubleshooting from a call that failed, so it belongs
      // beside the operations rather than in Docs. The folder stays where it
      // is, which is what keeps every published troubleshooting URL working.
      // Its index is the section header's own link, as APIs above.
      apiItems.push({
        type: 'category',
        label: 'Troubleshooting',
        className: 'sidebar-icon sidebar-icon--life-buoy',
        collapsed: false,
        link: {type: 'doc', id: `${pv}/troubleshooting/index`},
        items: [{type: 'autogenerated', dirName: `${pv}/troubleshooting`}],
      });
    }
    if (apiItems.length > 0) {
      sidebars[`${platform.name}-${version.name}-api`] = apiItems;
    }

    // Developer resources: testing use cases today, workflows and explanations
    // as they are written. Its own tab, so its own sidebar. Nothing to compose
    // here, unlike the API side: the folder is the section.
    // A gateway may publish its own What's new and Support. Each is its own
    // tab, so each gets its own sidebar; without the folder the tab falls
    // back to the site-wide page.
    for (const section of ['whats-new', 'support']) {
      if (hasDocs(join(docsRoot, pv, section))) {
        sidebars[`${platform.name}-${version.name}-${section}`] = [
          {type: 'autogenerated', dirName: `${pv}/${section}`},
        ];
      }
    }

    if (hasDocs(join(docsRoot, pv, 'resources'))) {
      sidebars[`${platform.name}-${version.name}-resources`] = [
        {type: 'autogenerated', dirName: `${pv}/resources`},
      ];
    }
  }
}

export default sidebars;
