/**
 * Navigation model for the portal.
 *
 * Routing follows the reference portal: /docs/<platform>/<version>/<section>.
 * The platform is chosen from a picker at the top of the sidebar, not from the
 * tab strip, so a reader who has chosen a gateway keeps that choice while
 * moving through its guides.
 */

import {useLocation} from '@docusaurus/router';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import generatedPlatforms from '../data/platforms.json';
import generatedReferenceLinks from '../data/reference-links.json';

export type Tab = {
  id: TabId;
  label: string;
  to: string;
  /** Route prefix that marks this tab active. */
  match: string;
};

export type Version = {
  label: string;
  /** Route for a version that exists here. Absent when it is not published. */
  to?: string;
  /** Why a reader cannot open it, shown in the picker. */
  note?: string;
};

export type Platform = {
  /** Short name, shown in the picker and in the breadcrumb. */
  id: string;
  label: string;
  /** One line under the label in the picker. */
  description: string;
  /** Version segment currently published for this platform. */
  version: string;
  /** Every version the picker offers, published or not. */
  versions: Version[];
  /** Where the API references tab sends the reader for this gateway. */
  apiTo: string;
  /** Where the picker sends the reader. */
  to: string;
  /** Route prefix that marks this platform current. */
  match: string;
};

// Generated by scripts/build-nav.mjs from the docs tree: one platform per
// docs/<platform> folder, one version per folder under it, labels and notes
// from each platform's _platform.json. Creating a folder is what adds an
// entry here; this file never lists platforms by hand.
export const platforms: Platform[] = generatedPlatforms;

export type TabId = 'overview' | 'api' | 'resources' | 'whats-new' | 'support';

// The default platform is the picker's first entry; a tab opened with no
// gateway chosen lands there.
/**
 * The page each per-gateway section tab opens, for the gateways that have one.
 *
 * Developer resources is on every gateway, and what it holds changes with the
 * gateway: HIE-CM's test scenarios, NHCX's FHIR reference and error codes, and
 * whatever a gateway publishes next (site/sidebars.ts composes it). A gateway
 * with a resources/ folder opens there; one without opens its first page.
 *
 * A gateway listed under What's new or Support publishes its own; every other
 * gateway, and every page outside one, uses the site-wide page.
 *
 * Listed here because platforms.json carries no section fields. Move them into
 * scripts/build-nav.mjs when the list grows.
 */
const SECTION_PAGES: Record<'resources' | 'whats-new' | 'support', Record<string, string>> = {
  resources: {hiecm: 'resources', nhcx: 'reference/fhir', uhi: 'resources'},
  'whats-new': {nhcx: 'whats-new'},
  support: {nhcx: 'support'},
};

/** Developer resources for the first gateway, for a page outside any gateway. */
const resourcesDefault = `${platforms[0].to}/${SECTION_PAGES.resources[platforms[0].id] ?? 'resources'}`;

// The same five tabs on every gateway. What sits under Developer resources is
// what changes between them.
export const tabs: Tab[] = [
  {id: 'overview', label: 'Docs', to: platforms[0].to, match: '/docs/'},
  {id: 'api', label: 'API reference', to: platforms[0].apiTo, match: '/api'},
  {id: 'resources', label: 'Developer resources', to: resourcesDefault, match: '/resources'},
  {id: 'whats-new', label: "What's new", to: '/docs/whats-new', match: '/docs/whats-new'},
  {id: 'support', label: 'Support', to: '/docs/support', match: '/docs/support'},
];

/** The tabs to show on a route: the same five everywhere. */
export function visibleTabs(_pathname: string): Tab[] {
  return tabs;
}

/** The href for a tab, keeping the gateway the reader already chose. */
export function tabHref(tab: Tab, pathname: string): string {
  const platform = activePlatform(pathname);
  if (!platform) {
    return tab.to;
  }
  if (tab.id === 'overview') {
    return platform.to;
  }
  if (tab.id === 'api') {
    return `${platform.to}/api`;
  }
  if (tab.id === 'resources') {
    return `${platform.to}/${SECTION_PAGES.resources[platform.id] ?? 'resources'}`;
  }
  if (tab.id === 'whats-new' || tab.id === 'support') {
    const page = SECTION_PAGES[tab.id][platform.id];
    return page ? `${platform.to}/${page}` : tab.to;
  }
  return tab.to;
}

/**
 * Interactive OpenAPI references, rendered by Scalar on their own routes.
 * Generated by scripts/build-nav.mjs: one entry per specification file in
 * the catalogue.
 */
export const referenceLinks: {label: string; to: string}[] = generatedReferenceLinks;

export function activePlatform(pathname: string): Platform | undefined {
  return platforms.find((platform) => pathname.startsWith(platform.match));
}

/**
 * True when a route belongs to the API side of a gateway.
 *
 * The API side is three folders, `api/`, `reference/` and `troubleshooting/`
 * (see site/sidebars.ts, which composes the API sidebar from exactly those).
 * All three are matched as whole path segments, at the end of a path as well
 * as in the middle, so a section index such as `/docs/hiecm/v3/api` counts the
 * same as a page beneath it.
 *
 * Troubleshooting is here rather than in Docs because a reader reaches it from
 * a failing call, which is an API reference question. It keeps its published
 * URL, `/docs/<platform>/<version>/troubleshooting/...`, because moving the
 * folder would break five live links to buy nothing.
 *
 * One predicate, exported, because this question is asked in more than one
 * place: the tab strip asks it to light the right tab, and the sidebar asks it
 * to decide whether to offer the version. They answered it differently once,
 * which is how a reference page lit the Docs tab while its sidebar showed the
 * API tree.
 */
export function isApiRoute(pathname: string): boolean {
  return /\/(api|reference|troubleshooting)(\/|$)/.test(pathname);
}

/** True for a FHIR reference page: `reference/fhir/` and beneath it. */
export function isFhirRoute(pathname: string): boolean {
  return /\/reference\/fhir(\/|$)/.test(pathname);
}

/** True for the error code pages: `reference/error-codes` and the guide. */
export function isErrorCodesRoute(pathname: string): boolean {
  return /\/reference\/(error-code(s|-guide)|pmjay-error-codes)(\/|$)/.test(pathname);
}

/**
 * True for a Developer resources page: the resources/ folder, and the FHIR
 * reference and error code pages, which keep their reference/ URLs but sit in
 * the Developer resources sidebar (site/sidebars.ts).
 */
export function isResourcesRoute(pathname: string): boolean {
  return /\/resources(\/|$)/.test(pathname) || isFhirRoute(pathname) || isErrorCodesRoute(pathname);
}

/**
 * Gateways whose API reference tab holds only api/: their other reference
 * pages and troubleshooting belong to Docs (SPLIT_REFERENCE in
 * site/sidebars.ts).
 */
const SPLIT_REFERENCE = new Set(['nhcx']);

/** True for the API reference tab, the one whose gateway switch keeps the reader on the APIs. */
export function isApiSideTab(id: TabId | undefined): boolean {
  return id === 'api';
}

/**
 * Which tab a route belongs to. The two short tabs own their own prefixes.
 * Everything else under a gateway is its Developer resources (which include
 * its FHIR reference and error codes), its API section, or its overview.
 */
export function activeTab(pathname: string): Tab | undefined {
  const short = tabs.find(
    (tab) =>
      (tab.id === 'whats-new' || tab.id === 'support') &&
      pathname.startsWith(tab.match),
  );
  if (short) {
    return short;
  }
  const platform = activePlatform(pathname);
  if (platform) {
    const own = /\/(whats-new|support)(\/|$)/.exec(pathname.slice(platform.match.length));
    if (own) {
      return tabs.find((tab) => tab.id === own[1]);
    }
    const apiSide = SPLIT_REFERENCE.has(platform.id)
      ? /\/api(\/|$)/.test(pathname)
      : isApiRoute(pathname);
    const id: TabId = isResourcesRoute(pathname) ? 'resources' : apiSide ? 'api' : 'overview';
    return tabs.find((tab) => tab.id === id);
  }
  return undefined;
}

/** The version the reader is on, or the platform's current one. */
export function activeVersion(platform: Platform, pathname: string): Version {
  return (
    platform.versions.find((v) => v.to && pathname.startsWith(v.to)) ??
    platform.versions.find((v) => v.label === platform.version) ??
    platform.versions[0]
  );
}

/**
 * The route, with the site's baseUrl stripped off the front. Every matcher
 * above is written against site-root paths ('/docs/...'), but the deployed
 * site sits under '/abdm-docs/', so a raw `useLocation().pathname` matches
 * none of them: the landing page stops looking like '/' and the whole chrome
 * appears on it. Read the route through this, never through useLocation.
 */
export function useRoutePath(): string {
  const {pathname} = useLocation();
  const {siteConfig} = useDocusaurusContext();
  const base = siteConfig.baseUrl;
  return base !== '/' && pathname.startsWith(base)
    ? `/${pathname.slice(base.length)}`
    : pathname;
}

/** True for the landing page, in dev at '/' and in a build at '/index.html'. */
export function isLanding(path: string): boolean {
  return path === '/' || path === '/index.html';
}
