/**
 * Scopes the API sidebar to the reader's chosen role.
 *
 * A module's roles are declared in its specification and reach here through
 * api-sidebar.json, so this never holds a list of modules itself.
 *
 * Filtering is by label because that is what the sidebar carries: the tree is
 * autogenerated from the docs folder, and a module category's label is the one
 * from its `_category_.json`, which build-api-reference.mjs writes from the
 * same spec that declares the roles.
 */
import {useMemo} from 'react';
import apiTree from '@site/src/data/api-sidebar.json';
import {activePlatform, platforms, useRoutePath} from './navigation';
import {moduleMatchesRole, useRole} from './roles';

type Item = {type?: string; label?: string; items?: Item[]};

export function useRoleScopedSidebar<T>(sidebar: T): T {
  const pathname = useRoutePath();
  const platform = activePlatform(pathname) ?? platforms[0];
  const [role] = useRole(platform.id);

  return useMemo(() => {
    if (!role || !Array.isArray(sidebar)) return sidebar;

    const rolesByLabel = new Map<string, string[]>();
    for (const entry of apiTree as any[]) {
      if (entry.platform === platform.id) rolesByLabel.set(entry.label, entry.roles ?? []);
    }
    if (rolesByLabel.size === 0) return sidebar;

    const keep = (items: Item[]): Item[] =>
      items
        .filter((item) => {
          const declared = item.label ? rolesByLabel.get(item.label) : undefined;
          // Only module categories are known here. Anything else, a guide
          // page or the References group, is left alone.
          return declared === undefined
            ? true
            : moduleMatchesRole(declared, platform.id, role);
        })
        .map((item) => (item.items ? {...item, items: keep(item.items)} : item));

    const scoped = keep(sidebar as Item[]);
    // Never hand back an empty tree: a role with nothing to show would leave
    // the reader with no navigation and no way to understand why.
    return (scoped.length > 0 ? scoped : sidebar) as T;
  }, [sidebar, role, platform.id]);
}
