// Mechanised checks over the Catalogue's atoms. Everything here is a rule the
// plan states, turned into something CI can fail on. An atom that passes this
// is well formed; whether it is honest is still a reviewer's job.
import { statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { loadAtoms, root } from "./lib/atoms.mjs";
import { contractProblems } from "./lib/contract.mjs";
import { loadOps } from "./lib/ops.mjs";
import { FOLDER } from "./lib/paths.mjs";

const TYPES = ["concept", "flow", "endpoint", "callback", "error", "test",
               "decision", "glossary", "fhir", "sandbox", "troubleshooting"];
const GATEWAYS = ["hiecm", "uhi", "nhcx", "shared"];

const problems = [];

function fail(file, msg) {
  problems.push(`${relative(root, file)}: ${msg}`);
}

const { atoms, problems: parseProblems } = loadAtoms();
for (const p of parseProblems) fail(p.file, p.msg);

// Only HIE-CM has specifications in this repository; an operation on any
// other gateway cannot resolve yet.
const contractCtx = {
  operations: { hiecm: new Set(loadOps(root).map((o) => o.operationId)) },
  atomIds: new Set(atoms.keys()),
};

for (const [id, atom] of atoms) {
  const { file, fm, body, raw } = atom;

  for (const field of ["id", "type", "gateway", "milestone", "version", "title", "summary", "sources", "related"]) {
    if (fm[field] === undefined) fail(file, `missing mandatory field: ${field}`);
  }
  if (!id) continue;

  if (!TYPES.includes(fm.type)) fail(file, `type must be one of ${TYPES.join(", ")}`);
  if (!GATEWAYS.includes(fm.gateway)) fail(file, `gateway must be one of ${GATEWAYS.join(", ")}`);

  // id is gateway.type.slug, lowercase, and must match where the file lives.
  if (!/^[a-z0-9]+\.[a-z]+\.[a-z0-9-]+$/.test(id)) fail(file, `id "${id}" is not gateway.type.slug in lowercase`);
  else {
    const [g, t] = id.split(".");
    if (g !== fm.gateway) fail(file, `id says gateway "${g}" but frontmatter says "${fm.gateway}"`);
    if (t !== fm.type) fail(file, `id says type "${t}" but frontmatter says "${fm.type}"`);
    if (FOLDER[fm.type] && !file.includes(`/${FOLDER[fm.type]}/`)) {
      fail(file, `type ${fm.type} must live in a ${FOLDER[fm.type]}/ folder`);
    }
  }

  if (fm.gateway === "shared" && fm.milestone !== "n/a") fail(file, "shared atoms take milestone: n/a");

  if (!Array.isArray(fm.sources) || fm.sources.length === 0) fail(file, "sources must list at least one entry");
  else fm.sources.forEach((s, i) => {
    if (!s?.url && !s?.file) fail(file, `sources[${i}] needs a url or a file`);
    if (!s?.status && !s?.hash) fail(file, `sources[${i}] needs a status or a hash`);
  });

  // No verification field: the Catalogue is published as ABDM's statement of how ABDM works.
  if (fm.verified !== undefined) fail(file, "verified is not a field; delete it");

  // Atom contract v2: sections per type, the operation join, facts, side
  // and status (scripts/lib/contract.mjs).
  for (const p of contractProblems(fm, body, contractCtx)) fail(file, p);

  // An atom must not name a site route. Atoms are built before the site and
  // are not published one to one as pages, so a route here is a guess that
  // rots. The mapping lives in catalogue/atom-routes.json, generated by
  // scripts/build-atom-routes.mjs from what the site actually publishes.
  if (fm.docs?.url !== undefined) {
    fail(file, "docs.url is not allowed on an atom. Page routes are generated into atom-routes.json, and a page may claim an atom with its own covers: key.");
  }

  // order is optional, and it decides where an atom sits in a compiled design
  // section. A string or a float silently sorts last instead of failing, so
  // the typo would be invisible until somebody read the skill.
  if (fm.order !== undefined && (!Number.isInteger(fm.order) || fm.order < 1)) {
    fail(file, `order must be a whole number from 1 upwards, got ${JSON.stringify(fm.order)}`);
  }

  // router is optional: the one line a compiled skill's always-loaded router
  // carries for this atom, where the design section is loaded on demand. An
  // empty or non-string value would render as a blank bullet.
  if (fm.router !== undefined && (typeof fm.router !== "string" || !fm.router.trim())) {
    fail(file, "router must be a non-empty string when present");
  }

  if (raw.includes("—")) fail(file, "em dash found. Use a full stop, a comma or a colon.");

  // Relative links in the body must point at a file that exists. A dead link
  // in an atom sends the reader hunting for something we already wrote.
  for (const m of body.matchAll(/\]\((\.[^)]+?\.md)\)/g)) {
    const target = join(dirname(file), m[1]);
    try { statSync(target); } catch { fail(file, `link points at "${m[1]}", which does not exist`); }
  }

  for (const [kind, ids] of Object.entries(fm.related ?? {})) {
    for (const ref of ids ?? []) {
      // ponytail: NHCX atoms are exempt until owner decision 1 (whether NHCX
      // stays merged in from NHA's fork). Eight of them list themselves, and an
      // edit here would be lost or conflict on the next merge. Drop the gateway
      // guard once that is decided and those eight are fixed at their source.
      if (ref === fm.id && fm.gateway !== "nhcx") fail(file, `related.${kind} lists the atom itself; remove "${ref}"`);
      if (!atoms.has(ref)) fail(file, `related.${kind} points at "${ref}", which no atom defines`);
    }
  }
}

const byType = {};
for (const a of atoms.values()) byType[a.fm?.type] = (byType[a.fm?.type] ?? 0) + 1;

console.log(`${atoms.size} atoms`);
console.log("  by type:  " + Object.entries(byType).map(([k, v]) => `${k} ${v}`).join(", "));

if (problems.length) {
  console.error(`\n${problems.length} problem(s):`);
  for (const p of problems) console.error("  " + p);
  process.exit(1);
}
console.log("\nAll atom rules pass.");
