// Validates compiled skills against the Catalogue they were built from.
// Failures here are build blockers: see `skill-compiler`.
//
// Checks: frontmatter parses and matches the directory name, every atom id
// cited resolves, every endpoint path cited exists in an atom, required
// sections are present, no em dash, and every OODA loop states an exit
// condition and a loop limit.
//
// The NHCX skills are checked too, by different rules. They are copied in from
// github.com/nha-in/nhcx-skills rather than compiled here, so nothing traces
// them to an atom. What can be checked is that each router is well formed, that
// the provenance block is current, and that the files every folder repeats are
// still byte identical across all seven. That last one is the rule that matters:
// 57 of each folder's 58 files are copies, so a fix applied to one folder and
// not the rest is the failure this catches.
//
// Usage: node scripts/validate-skills.mjs
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, relative } from "node:path";
import { parse } from "yaml";
import { loadAtoms, root } from "./lib/atoms.mjs";

const skillsDir = join(root, "skills-src");
const nhcxDir = join(root, "plugins", "nhcx", "skills");
const { atoms } = loadAtoms();

const KNOWN_PATHS = new Set();
for (const a of atoms.values()) {
  for (const m of a.raw.matchAll(/'(https?:\/\/[^']+)'/g)) KNOWN_PATHS.add(m[1]);
}

// Compiled OODA skills are named hiecm-<milestone>-build and -debug, so the
// rule is stated once and applies to every milestone the compiler emits.
// Naming them one by one is how a new milestone ships unchecked.
function requiredSections(name) {
  if (/^hiecm-[a-z0-9-]+-build$/.test(name)) return ["## Journeys"];
  if (/^hiecm-[a-z0-9-]+-debug$/.test(name)) return ["## Errors"];
  return null;
}

let failures = [];
function fail(skill, msg) { failures.push(`${skill}: ${msg}`); }

for (const name of readdirSync(skillsDir)) {
  const file = join(skillsDir, name, "SKILL.md");
  if (!existsSync(file)) continue; // README.md and other non-skill entries
  const raw = readFileSync(file, "utf8");
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) { fail(name, "no frontmatter block"); continue; }

  let fm;
  try { fm = parse(m[1]); } catch (e) { fail(name, `frontmatter is not valid YAML: ${e.message}`); continue; }
  if (fm.name !== name) fail(name, `frontmatter name "${fm.name}" does not match directory`);
  if (!fm.description) fail(name, "missing description");

  const body = m[2];
  if (raw.includes("—")) fail(name, "em dash found");

  const required = requiredSections(name);
  for (const heading of required ?? []) {
    if (!body.includes(heading)) fail(name, `missing required section: ${heading}`);
  }

  // Every atom id the skill cites must exist in the Catalogue.
  for (const m2 of body.matchAll(/`((?:hiecm|shared)\.[a-z]+\.[a-z0-9-]+)`/g)) {
    if (!atoms.has(m2[1])) fail(name, `cites atom "${m2[1]}", which the Catalogue does not define`);
  }

  // Every curl URL the skill prints must be one an atom actually recorded.
  for (const m3 of body.matchAll(/'(https?:\/\/[^']+)'/g)) {
    if (!KNOWN_PATHS.has(m3[1])) fail(name, `curl target "${m3[1]}" is not recorded on any atom`);
  }

  // Every loop needs a stated limit and every flow/error block needs an
  // exit condition, or an agent following it cannot terminate correctly.
  // These two rules describe the compiled OODA skills (the ones with
  // required sections); hand-authored skills state their own done
  // conditions in prose and are reviewed by hand.
  if (required) {
    if (!/Loop limit: \d+ passes? per/.test(body)) fail(name, "no loop limit stated");
    const blocks = body.split(/\n### /).length - 1;
    const exitMentions = (body.match(/Exit condition/g) ?? []).length;
    if (blocks > 0 && exitMentions < blocks) {
      fail(name, `${blocks} loop(s) but only ${exitMentions} exit condition(s)`);
    }
  }
}

// The NHCX skills: well formed, stamped, and every link inside them resolving.
const NHCX_PROVENANCE = "<!-- provenance: generated by scripts/stamp-nhcx-skills.mjs";
const nhcxSlugs = existsSync(nhcxDir)
  ? readdirSync(nhcxDir).filter((n) => existsSync(join(nhcxDir, n, "SKILL.md"))).sort()
  : [];

/** Every file in a skill folder, by path relative to that folder, hashed. */
function folderFiles(dir) {
  const out = new Map();
  const walk = (d) => {
    for (const entry of readdirSync(d, { withFileTypes: true })) {
      const full = join(d, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.isFile()) {
        out.set(relative(dir, full), createHash("sha256").update(readFileSync(full)).digest("hex"));
      }
    }
  };
  walk(dir);
  return out;
}

for (const slug of nhcxSlugs) {
  const file = join(nhcxDir, slug, "SKILL.md");
  const raw = readFileSync(file, "utf8");
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) { fail(slug, "no frontmatter block"); continue; }
  let fm;
  try { fm = parse(m[1]); } catch (e) { fail(slug, `frontmatter is not valid YAML: ${e.message}`); continue; }
  if (fm.name !== slug) fail(slug, `frontmatter name "${fm.name}" does not match directory`);
  if (!fm.description) fail(slug, "missing description");
  if (!m[2].includes(NHCX_PROVENANCE)) {
    fail(slug, "no provenance block. Run: node scripts/stamp-nhcx-skills.mjs");
  }
  // The em dash rule is repository wide. Every relative link, in the router
  // and in every file it leads to, has to land inside the folder: a skill
  // installs alone, so a link out of it points at a file the reader does not
  // have. Each skill holds only the specs its goal needs, so the folders are
  // not copies of one another and no longer have to match.
  for (const [rel] of folderFiles(join(nhcxDir, slug))) {
    if (!/\.(md|json|sh)$/.test(rel)) continue;
    const text = readFileSync(join(nhcxDir, slug, rel), "utf8");
    if (text.includes("\u2014")) fail(slug, `em dash found in ${rel}`);
    if (!rel.endsWith(".md")) continue;
    for (const [, target] of text.matchAll(/\]\(([^)\s]+)\)/g)) {
      if (/^(https?:|mailto:|#)/.test(target)) continue;
      const path = target.split("#")[0];
      if (!path) continue;
      const resolved = join(nhcxDir, slug, dirname(rel), path);
      if (!resolved.startsWith(join(nhcxDir, slug))) fail(slug, `${rel} links out of the folder: ${target}`);
      else if (!existsSync(resolved)) fail(slug, `${rel} links to a missing file: ${target}`);
    }
  }
}

if (failures.length) {
  console.error(`${failures.length} problem(s):`);
  for (const f of failures) console.error(`  ${f}`);
  process.exit(1);
}
console.log(`All compiled skills trace back to the Catalogue. ${nhcxSlugs.length} NHCX skill(s) are well formed, stamped, and every link in them resolves.`);
