// Package catalogue parses the ABDM catalogue: atom markdown files with
// YAML frontmatter, the OpenAPI specifications, and body chunking.
package catalogue

import (
	"bytes"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type Atom struct {
	ID        string
	Type      string
	Gateway   string
	Milestone string
	Title     string
	Summary   string
	// Audience is "contributor" on an atom that documents how this
	// catalogue is built rather than how ABDM is integrated. Empty means
	// integrator, so an atom is integrator-facing unless it says
	// otherwise. The indexer drops contributor atoms, which is what keeps
	// the MCP server, the Ask AI panel and site search to one audience.
	Audience   string
	Body       string
	SourcePath string
	// DocURL and DocAnchor are the published page a support answer links
	// to instead of showing a reader an atom id, and the section within
	// it. They are NOT parsed from the atom: an atom is authored before
	// the site exists and is not published one to one as a page, so it
	// cannot know its own route. The indexer fills these from
	// catalogue/atom-routes.json, generated by scripts/build-atom-routes.mjs
	// from what the site actually publishes. Empty means the atom has no
	// published page, and callers must not cite it to a reader.
	DocURL     string
	DocAnchor  string
	ErrorCodes []string
	Related    map[string][]string

	// Atom contract v2. Operation joins an endpoint or callback atom to its
	// operationId. Side narrows who it is for (provider, payer, hip, hiu,
	// both). Status is current, deprecated or draft; a deprecated atom is
	// hidden from search unless asked for, and SupersededBy names what
	// replaced it. Facts are values to quote exactly, each citing a source.
	Operation    string
	Side         string
	Status       string
	SupersededBy string
	Facts        []Fact
	// Generated marks an atom scripts/build-sections.mjs wrote from its page
	// section; it sits beside hand-written atoms in its type folder.
	Generated bool
}

// Fact is one value an answer should quote exactly, with the index into the
// atom's sources that states it.
type Fact struct {
	Key    string
	Value  string
	Source int
}

type frontmatter struct {
	ID        string              `yaml:"id"`
	Type      string              `yaml:"type"`
	Gateway   string              `yaml:"gateway"`
	Milestone string              `yaml:"milestone"`
	Title     string              `yaml:"title"`
	Summary   string              `yaml:"summary"`
	Audience  string              `yaml:"audience"`
	Related   map[string][]string `yaml:"related"`

	Operation    string `yaml:"operation"`
	Side         string `yaml:"side"`
	Status       string `yaml:"status"`
	SupersededBy string `yaml:"superseded_by"`
	Generated    bool   `yaml:"generated"`
	Facts        []struct {
		Key    string `yaml:"key"`
		Value  any    `yaml:"value"`
		Source int    `yaml:"source"`
	} `yaml:"facts"`
}

// HIS is M4's registry series and AS is the PHR series NHA records once
// against P1. Both were missing, so decode_error answered "no error codes
// found" for 572 codes the catalogue holds.
//
// NHCX and PAYR are the claims exchange's two families, the exchange's own
// codes and the payer's, and ERR-PYR-CLM-007 is the one the scheme's payer
// sends in a third shape. None of the three was here, so decode_error answered
// "no error codes found" for all 310 codes the catalogue holds for NHCX.
var errCodeRe = regexp.MustCompile(`\b(?:(?:ABDM|GATEWAY|MIS|HIS|AS|NHCX|PAYR)-\d{3,5}|ERR-PYR-[A-Z]{2,5}-\d{3})\b`)

// gatewayCodeRe matches the gateway's numeric authentication codes (900900,
// 900901, 900902) only as a JSON "code" value, so a bare six-digit number
// elsewhere in the input (an OTP, a timestamp) is not read as a code.
var gatewayCodeRe = regexp.MustCompile(`"code"\s*:\s*"?(9\d{5})\b`)

func ExtractErrorCodes(s string) []string {
	set := map[string]bool{}
	for _, c := range errCodeRe.FindAllString(s, -1) {
		set[strings.ToUpper(c)] = true
	}
	for _, m := range gatewayCodeRe.FindAllStringSubmatch(s, -1) {
		set[m[1]] = true
	}
	var out []string
	for c := range set {
		out = append(out, c)
	}
	sort.Strings(out)
	return out
}

func ParseAtom(sourcePath string, content []byte) (Atom, error) {
	rest, ok := bytes.CutPrefix(content, []byte("---\n"))
	if !ok {
		return Atom{}, fmt.Errorf("%s: missing frontmatter", sourcePath)
	}
	fmBytes, body, ok := bytes.Cut(rest, []byte("\n---\n"))
	if !ok {
		return Atom{}, fmt.Errorf("%s: unterminated frontmatter", sourcePath)
	}
	var fm frontmatter
	if err := yaml.Unmarshal(fmBytes, &fm); err != nil {
		return Atom{}, fmt.Errorf("%s: frontmatter: %w", sourcePath, err)
	}
	if fm.ID == "" {
		return Atom{}, fmt.Errorf("%s: frontmatter missing id", sourcePath)
	}
	related := fm.Related
	if related == nil {
		related = map[string][]string{}
	}
	status := fm.Status
	if status == "" {
		status = "current"
	}
	var facts []Fact
	for _, f := range fm.Facts {
		// A value may be written as a number or a word (202, 6 months);
		// it is quoted as written.
		facts = append(facts, Fact{Key: f.Key, Value: fmt.Sprint(f.Value), Source: f.Source})
	}
	return Atom{
		ID:           fm.ID,
		Type:         fm.Type,
		Gateway:      fm.Gateway,
		Milestone:    fm.Milestone,
		Title:        fm.Title,
		Summary:      strings.TrimSpace(fm.Summary),
		Audience:     fm.Audience,
		Body:         strings.TrimSpace(string(body)),
		SourcePath:   sourcePath,
		ErrorCodes:   ExtractErrorCodes(string(content)),
		Related:      related,
		Operation:    fm.Operation,
		Side:         fm.Side,
		Status:       status,
		SupersededBy: fm.SupersededBy,
		Facts:        facts,
		Generated:    fm.Generated,
	}, nil
}
