#!/usr/bin/env bash
# Publish the public plugin marketplace, nha-in/agent-plugins, from this repository's build.
#
#   deploy/nha/publish-agent-plugins.sh <version>      e.g. deploy/nha/publish-agent-plugins.sh v1.1.3
#
# deploy.sh runs this after the site build and before the site upload, so the public repository
# carries the plugins before the site's install commands point at them, and a failed publish stops
# the deploy before anything goes live. It can also run alone after `npm run build`.
#
# It keeps a clone of the public repository at AGENT_PLUGINS_DIR (default: ../agent-plugins beside
# this repository), cloning it when missing, brings it level with origin, rewrites it from the build
# with scripts/publish-agent-plugins.mjs, and when anything changed commits, tags <version> and
# pushes. Pushing uses the deployer's own git credentials. AGENT_PLUGINS_PUBLISH=0 skips it;
# AGENT_PLUGINS_PUSH=0 does everything but the push, to see what a publish would change.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
repo="$(cd "$here/../.." && pwd)"
VERSION="${1:?usage: deploy/nha/publish-agent-plugins.sh <version>}"

if [[ "${AGENT_PLUGINS_PUBLISH:-1}" == "0" ]]; then
  echo "==> agent plugins: skipped (AGENT_PLUGINS_PUBLISH=0)"
  exit 0
fi

public_repo="$(node -e "console.log(require('$repo/publish/agent-plugins.json').repo)")"
dir="${AGENT_PLUGINS_DIR:-$(cd "$repo/.." && pwd)/agent-plugins}"

if [[ ! -d "$dir/.git" ]]; then
  echo "==> agent plugins: cloning $public_repo to $dir"
  git clone --quiet "git@github.com:$public_repo.git" "$dir"
fi

remote="$(git -C "$dir" remote get-url origin)"
if [[ "$remote" != *"$public_repo"* ]]; then
  echo "$dir is a clone of $remote, not $public_repo" >&2
  exit 1
fi

# Level with origin first, so the publish never rewrites a stale copy. An empty public repository
# has no origin/main yet, which is fine: the first push creates it.
git -C "$dir" fetch --quiet origin
if git -C "$dir" rev-parse --verify --quiet origin/main >/dev/null; then
  if ! git -C "$dir" merge --quiet --ff-only origin/main; then
    echo "$dir has commits origin/main does not; resolve them there first" >&2
    exit 1
  fi
fi

echo "==> agent plugins: publishing $VERSION to $public_repo"
node "$repo/scripts/publish-agent-plugins.mjs" "$dir"

git -C "$dir" add -A
if git -C "$dir" diff --cached --quiet; then
  echo "    no plugin changed since the last publish"
else
  git -C "$dir" commit --quiet \
    -m "Publish from the ABDM Developer Portal $VERSION" \
    -m "Generated by scripts/publish-agent-plugins.mjs from the portal repository at $(git -C "$repo" rev-parse --short HEAD)."
fi

# The tag marks which portal release a plugin version shipped with. A tag already on another
# commit is left alone rather than moved.
if ! git -C "$dir" rev-parse --verify --quiet "refs/tags/$VERSION" >/dev/null; then
  git -C "$dir" tag "$VERSION"
fi

if [[ "${AGENT_PLUGINS_PUSH:-1}" == "0" ]]; then
  echo "    not pushed (AGENT_PLUGINS_PUSH=0); $dir holds the commit"
  exit 0
fi
git -C "$dir" push --quiet origin main
git -C "$dir" push --quiet origin "refs/tags/$VERSION" 2>/dev/null || echo "    tag $VERSION already on origin; left as it is"
echo "    published: https://github.com/$public_repo"
