#!/usr/bin/env bash
# Publish the public plugin marketplace, nha-in/agent-plugins, from this repository's build.
#
#   deploy/nha/publish-agent-plugins.sh <version>      e.g. deploy/nha/publish-agent-plugins.sh v1.1.3
#
# deploy.sh runs this after the site build and before the site upload, so the public repository
# carries the plugins before the site's install commands point at them, and a failed publish stops
# the deploy before anything goes live. It can also run alone after `npm run build`.
#
# Nothing is kept or edited by hand: each run clones the public repository into a temporary
# folder, rewrites it from the build with scripts/publish-agent-plugins.mjs, and when a plugin
# changed commits, tags <version> and pushes, then deletes the folder. Pushing uses the deployer's
# own git credentials. AGENT_PLUGINS_PUBLISH=0 skips it; AGENT_PLUGINS_PUSH=0 does everything but
# the push and prints what would have been published.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
repo="$(cd "$here/../.." && pwd)"
VERSION="${1:?usage: deploy/nha/publish-agent-plugins.sh <version>}"

if [[ "${AGENT_PLUGINS_PUBLISH:-1}" == "0" ]]; then
  echo "==> agent plugins: skipped (AGENT_PLUGINS_PUBLISH=0)"
  exit 0
fi

public_repo="$(node -e "console.log(require('$repo/publish/agent-plugins.json').repo)")"
remote="${AGENT_PLUGINS_REMOTE:-git@github.com:$public_repo.git}"
dir="$(mktemp -d)"
trap 'rm -rf "$dir"' EXIT

echo "==> agent plugins: publishing $VERSION to $public_repo"
git clone --quiet "$remote" "$dir" 2>/dev/null || git clone "$remote" "$dir"
# An empty repository clones with no branch; the first publish creates main.
if ! git -C "$dir" rev-parse --verify --quiet HEAD >/dev/null; then
  git -C "$dir" symbolic-ref HEAD refs/heads/main
fi

node "$repo/scripts/publish-agent-plugins.mjs" "$dir" >/dev/null

git -C "$dir" add -A
if git -C "$dir" diff --cached --quiet; then
  echo "    no plugin changed since the last publish"
  exit 0
fi
git -C "$dir" diff --cached --stat | tail -1 | sed 's/^/    /'
git -C "$dir" commit --quiet \
  -m "Publish from the ABDM Developer Portal $VERSION" \
  -m "Generated by scripts/publish-agent-plugins.mjs from the portal repository at $(git -C "$repo" rev-parse --short HEAD)."
# The tag marks which portal release a plugin version shipped with. One already published is left.
tag=1
if git -C "$dir" rev-parse --verify --quiet "refs/tags/$VERSION" >/dev/null; then
  echo "    tag $VERSION already exists there; left as it is"
  tag=0
else
  git -C "$dir" tag "$VERSION"
fi

if [[ "${AGENT_PLUGINS_PUSH:-1}" == "0" ]]; then
  echo "    not pushed (AGENT_PLUGINS_PUSH=0)"
  exit 0
fi
git -C "$dir" push --quiet origin main
if [[ "$tag" == "1" ]]; then git -C "$dir" push --quiet origin "refs/tags/$VERSION"; fi
echo "    published to $remote"
